# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5010dc5d99e036bb866fe0cdf312c47a0ff82ef07061e9c2be09deabc25c42d7f048968b221066cfc0d0fa5137fda0ba4a963823e9a8972a2c35e011f87d7de7

test:
  secret_key_base: 90cf0880f4b86ca6b6124fd2c56476545dc20a785c1bea0550ddec539d91e62f768cc034e2562f0b013402b40a527e9409ee6b4ccb490d836db4cc2c2866c8ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
